# Generated by Django 4.2.7 on 2023-12-06 06:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter_price',
            name='price',
            field=models.CharField(choices=[('500 To 1000', '500 To 1000'), ('1000 To 1500', '1000 To 1500'), ('1500 To 2000', '1500 To 2000'), ('2000 To 2500', '2000 To 2500'), ('2500 To 3000', '2500 To 3000'), ('3000 To 3500', '3000 To 3500'), ('3500 To 4000', '3500 To 4000'), ('4000 To 5000', '4000 To 5000')], max_length=60),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='Product_images/img'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='Product_images/img'),
        ),
        migrations.AlterField(
            model_name='product',
            name='information',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
