# Generated by Django 4.2.7 on 2024-01-26 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0009_remove_order_additional_info_alter_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='contry',
            new_name='country',
        ),
    ]
