# Generated by Django 4.2.7 on 2024-04-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0012_orderitem_user_alter_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
