# Generated by Django 4.2.7 on 2024-04-25 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0013_order_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='orderid',
        ),
    ]
