# Generated by Django 4.2.7 on 2024-04-25 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0014_rename_order_id_order_orderid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orderid',
            new_name='order_id',
        ),
    ]
